src/js/app.js
src/js/directives/elastic.js
src/sass/views/includes/txp-details.scss
www/css/main.css
www/index.html
www/views/includes/walletHistory.html
www/views/tx-details.html

Update: Fixes memo cut-off, changes memo to textarea, auto-expand based on content length, display memo while transaction is in Receiving state

BW-235 & BW-236

---

src/js/controllers/preferencesPriceDisplay.js
src/js/controllers/tab-home.js
src/js/controllers/tab-settings.js
src/js/controllers/walletDetails.js
src/js/routes.js
src/js/services/configService.js
src/js/services/openURL.js
src/js/services/uxLanguage.js
www/css/bitcoin.com.css
www/views/includes/walletList.html
www/views/preferencesPriceDisplay.html
www/views/tab-settings.html
www/views/walletDetails.html

Improvements : 172, 270, 247
Fix : 287

Improvements & fix

---

src/js/controllers/tab-receive.js

Improvement

---

app-template/package-template.json
i18n/po/template.pot
src/js/controllers/amount.js
src/js/controllers/tab-send.js
src/sass/views/amount.scss
www/css/main.css
www/img/icon-convert.svg
www/views/amount.html
www/views/tab-send.html

Sendscreen

---

www/views/tab-home.html

Improvement : 304

---

src/js/routes.js

Fix - 337 - Fix error for browser version

---

app-template/bitcoincom/appConfig.json
src/js/controllers/preferences.js
src/js/controllers/tx-details.js

Fixing two links that pointed to the wrong repo that I came across in the wallet.

Fixing two links

---

src/js/controllers/communityController.js
src/js/controllers/nextStepsController.js
src/js/controllers/tx-details.js

With this, also the "View on Blockchain" button is fixed with this on Desktop builds

Improvement - 355 - Use External Link Service

---

src/sass/views/includes/slideToAcceptSuccess.scss

Small Fix for iPhoneX, all slide-to-accept screens are affected.

Improvement - 376 - More Adjustments for iPhone X

---

src/sass/views/includes/walletSelector.scss
src/sass/views/tab-home.scss
www/views/includes/walletSelector.html
www/views/tab-home.html

Changes as requested, for more consistent spacing.

Improvement 384 - New Wallet headers design

---

src/js/services/configService.js

Improvement - 202 - Enable sound by default

---

src/js/controllers/tab-receive.js

Dismiss screen after changing screens..

Improvement - 378 - Dismiss "Received payment" screen

---

i18n/po/ca/template-ca.po
i18n/po/cs/template-cs.po
i18n/po/de/template-de.po
i18n/po/es-ES/template-es-ES.po
i18n/po/fa/template-fa.po
i18n/po/fr/template-fr.po
i18n/po/ja/template-ja.po
i18n/po/ko/template-ko.po
i18n/po/nl/template-nl.po
i18n/po/pl/template-pl.po
i18n/po/pt-BR/template-pt-BR.po
i18n/po/ru/template-ru.po
i18n/po/sv-SE/template-sv-SE.po
i18n/po/vi/template-vi.po
i18n/po/zh-CN/template-zh-CN.po
src/js/services/uxLanguage.js

Also updated existing translations.

Improvement 371 - Added Catalan and Russian translations.

---

app-template/config-template.xml

Forked the original media plugin from apache.

484 - Android: Remove permission for Microphone use

---

src/js/controllers/onboarding/tour.js

- In the end it was also happening with all other non-USD fiat currencies.
- On wallet creation it now waits for the rateService to gather the currency information

Bug - 490 - Korean Won isn't automatically selected when phone is in Korean (fiat currency)

---

src/js/controllers/review.controller.js

This is being merged into sprint 21 because it is for the next 5.1 RC.

590 - The Personal Note field is not cleared between transactions.

---

src/js/services/latest-release.service.js

Fix - 592 - Regex update for support for other release tags than "rc" in the latest release service

---

src/js/routes.js
src/js/services/buy-bitcoin-com.service.js

Restored the functionality of the Buy Bitcoin service registering itself.

557 - New translations

---

src/js/controllers/buy-bitcoin/add-card-form.controller.js
src/js/directives/directives.js
src/sass/components/apl.scss
www/views/buy-bitcoin/add-card-form.html

601 - Validation fixes and behavior update

---

.gitignore
src/js/controllers/customAmount.js
src/js/controllers/tab-receive.js

Using our own websocket instead of blockchain.info

Use our own source for the websocket

---

i18n/po/bg/template-bg.po
i18n/po/ca/template-ca.po
i18n/po/cs/template-cs.po
i18n/po/de/template-de.po
i18n/po/es-ES/template-es-ES.po
i18n/po/fa/template-fa.po
i18n/po/fr/template-fr.po
i18n/po/it/template-it.po
i18n/po/ja/template-ja.po
i18n/po/ko/template-ko.po
i18n/po/nl/template-nl.po
i18n/po/pl/template-pl.po
i18n/po/pt-BR/template-pt-BR.po
i18n/po/ru/template-ru.po
i18n/po/sv-SE/template-sv-SE.po
i18n/po/template.pot
i18n/po/vi/template-vi.po
i18n/po/zh-CN/template-zh-CN.po
src/js/controllers/tx-details.js
src/js/routes.js
www/views/tx-details.html

Removed the display of the conversion rate, as it will be dealt with differently in issue 736.

638 - Fix price conversion rate on Transaction Detail screen

---

i18n/po/template.pot
src/js/controllers/marco-coino.controller.js

Add error message if email account isn't available.

684 - Marco Coino Integration

---

src/js/controllers/tab-spend.controller.js
src/sass/components/apl.scss
src/sass/views/tab-spend.scss

Better formatting of multiline subtitles, and added campaign info to Bitcoin.com merchant links.

654 - Spend screen tweaks

---

src/js/controllers/marco-coino.controller.js

I don't know why this change is needed, but the previous code that theoretically should work, does not work on Android devices.
This needs to be tested on Android devices, as I only had the emulator available to me when creating the fix.

811 - Marco Coino map does not start at user's location on Android

---

src/js/controllers/buy-bitcoin/home.controller.js
src/js/controllers/buy-bitcoin/kyc-personal-info.controller.js
src/js/controllers/buy-bitcoin/kyc-status.controller.js
src/js/services/kyc-flow/kyc-flow-router.service.js
src/js/services/kyc-flow/kyc-flow-state.service.js
src/js/services/onGoingProcess.js
www/views/buy-bitcoin/home.html
www/views/buy-bitcoin/kyc-personal-info.html

- Review `home.html` and `home.controller.js` logic (see detailed explanation below)
- Remove `kyc-personal-info` tab from the KYC flow router and state
- Update `kyc-personal-info.controller.js` to submit form when click on “Submit”
**Different states of Buy Bitcoin Home screen**
1. User without personal info
- What to show
- Subtitle is “In order to purchase Bitcoin Cash, you are required to provide some personal information”
- Main button is “Provide my information”
- Do not show “Increase purchase limit”
- How to detect
- User does not have an identity check AND user dailyLimit and monthlyLimit are 0
2. User with personal info but no completed identity check
- What to show
- Subtitle is “You can purchase up to X today, and up to Y this month.“
- Main button is “Buy Bitcoin Cash”
- …

Review Buy Bitcoin KYC flow

---

www/views/includes/incomingDataMenu.html
www/views/paperWallet.html

Added screenshots of fix in action to JIRA Ticket.
https://bitcoindotcom.atlassian.net/browse/BW-826

Fixed issue with un-translated lines by adding context string.

---

src/js/controllers/buy-bitcoin/amount.controller.js
src/js/controllers/buy-bitcoin/kyc-personal-info.controller.js
src/js/controllers/buy-bitcoin/kyc-status.controller.js

Additional fixes for kyc date of birth field.

828 - Minor fixes

---

i18n/po/ar/template-ar.po
i18n/po/bg/template-bg.po
i18n/po/ca/template-ca.po
i18n/po/cs/template-cs.po
i18n/po/de/template-de.po
i18n/po/fa/template-fa.po
i18n/po/hi/template-hi.po
i18n/po/it/template-it.po
i18n/po/ko/template-ko.po
i18n/po/nl/template-nl.po
i18n/po/pl/template-pl.po
i18n/po/pt-BR/template-pt-BR.po
i18n/po/ru/template-ru.po
i18n/po/sv-SE/template-sv-SE.po
i18n/po/th/template-th.po
i18n/po/vi/template-vi.po
src/js/directives/formattedAmount.js
src/js/services/uxLanguage.js

5 - Update translations

---

src/js/controllers/review.controller.js
src/js/services/goCryptoService.js

We've changed some error messages in order to become more user-friendly.

Improve GoCrypto error messages
